import Api from "@/components/fetch";
import dynamic from "next/dynamic";
import React from "react";
const Postscard = dynamic(() => import("@/components/Cards-post"), {
  ssr: false,
  loading: () => <h2>Loading Card posts ...</h2>,
});
export const metadata = {
  title: "App route Posts",
  description: "Generated by create next app",
};
export default async function page() {
  const data = await Api("https://dummyjson.com/posts");
  console.log(data);
  return (
    <div>
      <Postscard dataapi={data} />
    </div>
  );
}
