import Api from "@/components/fetch";
import RecipeCardFull from "@/components/recipesCard";

import React from "react";

export async function generateMetadata({ params, searchParams }) {
  return {
    title: `App route recipes - ${params.nima}`,
    description: "Generated by create next app",
  };
}

export default async function page({ params }) {
  const data = await Api(`https://dummyjson.com/recipes/${params.nima}`);
  console.dir(data);
  if (data.message) throw new Error(data.message);
  return (
    <div>
      <RecipeCardFull recipe={data} />
    </div>
  );
}
