import Api from "@/components/fetch";
import dynamic from "next/dynamic";
import React from "react";
const RecipesCard = dynamic(() => import("@/components/Cord-recipes"), {
  ssr: false,
  loading: () => <h2>Loading Card recipes ...</h2>,
});
export const metadata = {
  title: "App route recipes",
  description: "Generated by create next app",
};
export default async function page() {
  const data = await Api("https://dummyjson.com/recipes");
  console.log(data);
  return (
    <div>
      <RecipesCard dataapi={data} />
    </div>
  );
}
