import Api from "@/components/fetch";
import dynamic from "next/dynamic";
import React from "react";
const ActionAreaCard = dynamic(() => import("@/components/Cards"), {
  ssr: false,
  loading: () => <h2>Loading Card user ...</h2>,
});
export const metadata = {
  title: "App route users",
  description: "Generated by create next app",
};
export default async function page() {
  const data = await Api("https://dummyjson.com/users");
  console.log(data);
  return (
    <div>
      <ActionAreaCard dataapi={data} />
    </div>
  );
}
